// <auto-generated />
using FoodWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221118102658_newFoodMigration")]
    partial class newFoodMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("FoodWebAPI.Models.Data.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecipieId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.HasIndex("RecipieId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Name = "Rice",
                            Quantity = 2m,
                            RecipieId = 1,
                            Unit = "grams"
                        },
                        new
                        {
                            IngredientId = 2,
                            Name = "Tomatoes",
                            Quantity = 10m,
                            RecipieId = 1,
                            Unit = "Sachet"
                        },
                        new
                        {
                            IngredientId = 3,
                            Name = "Yam",
                            Quantity = 2m,
                            RecipieId = 2,
                            Unit = "Tuber"
                        },
                        new
                        {
                            IngredientId = 4,
                            Name = "Plantain",
                            Quantity = 5m,
                            RecipieId = 2,
                            Unit = "Sticks"
                        });
                });

            modelBuilder.Entity("FoodWebAPI.Models.Data.Recipie", b =>
                {
                    b.Property<int>("RecipieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TimeToCook")
                        .HasColumnType("float");

                    b.Property<bool>("isVeganFood")
                        .HasColumnType("bit");

                    b.HasKey("RecipieId");

                    b.ToTable("Recipies");

                    b.HasData(
                        new
                        {
                            RecipieId = 1,
                            Method = "Boiling",
                            Name = "Jollof",
                            TimeToCook = 185.33333333333334,
                            isVeganFood = false
                        },
                        new
                        {
                            RecipieId = 2,
                            Method = "Boiling",
                            Name = "Ampesi",
                            TimeToCook = 59.75,
                            isVeganFood = true
                        });
                });

            modelBuilder.Entity("FoodWebAPI.Models.Data.Ingredient", b =>
                {
                    b.HasOne("FoodWebAPI.Models.Data.Recipie", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodWebAPI.Models.Data.Recipie", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
